// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.malsolo.courses.domain;

import com.malsolo.courses.domain.Professor;
import com.malsolo.courses.domain.ProfessorDataOnDemand;
import com.malsolo.courses.repository.ProfessorRepository;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ProfessorDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ProfessorDataOnDemand: @Component;
    
    private Random ProfessorDataOnDemand.rnd = new SecureRandom();
    
    private List<Professor> ProfessorDataOnDemand.data;
    
    @Autowired
    ProfessorRepository ProfessorDataOnDemand.professorRepository;
    
    public Professor ProfessorDataOnDemand.getNewTransientProfessor(int index) {
        Professor obj = new Professor();
        setLastName(obj, index);
        setName(obj, index);
        setSecondLastName(obj, index);
        return obj;
    }
    
    public void ProfessorDataOnDemand.setLastName(Professor obj, int index) {
        String lastName = "lastName_" + index;
        if (lastName.length() > 100) {
            lastName = lastName.substring(0, 100);
        }
        obj.setLastName(lastName);
    }
    
    public void ProfessorDataOnDemand.setName(Professor obj, int index) {
        String name = "name_" + index;
        if (name.length() > 50) {
            name = name.substring(0, 50);
        }
        obj.setName(name);
    }
    
    public void ProfessorDataOnDemand.setSecondLastName(Professor obj, int index) {
        String secondLastName = "secondLastName_" + index;
        if (secondLastName.length() > 100) {
            secondLastName = secondLastName.substring(0, 100);
        }
        obj.setSecondLastName(secondLastName);
    }
    
    public Professor ProfessorDataOnDemand.getSpecificProfessor(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Professor obj = data.get(index);
        Long id = obj.getId();
        return professorRepository.findOne(id);
    }
    
    public Professor ProfessorDataOnDemand.getRandomProfessor() {
        init();
        Professor obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return professorRepository.findOne(id);
    }
    
    public boolean ProfessorDataOnDemand.modifyProfessor(Professor obj) {
        return false;
    }
    
    public void ProfessorDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = professorRepository.findAll(new org.springframework.data.domain.PageRequest(from / to, to)).getContent();
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Professor' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Professor>();
        for (int i = 0; i < 10; i++) {
            Professor obj = getNewTransientProfessor(i);
            try {
                professorRepository.save(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            professorRepository.flush();
            data.add(obj);
        }
    }
    
}
